### ISSUE TITLE
"Print a custom receipt" sample does not work

### ISSUE THREAD

**Issue by DaSpors** [developermypos/myPOS-Smart-SDK#1]
Situation: myPOS Smart N5 in Debug Mode connected to Android Studio via USB.

https://github.com/developermypos/myPOS-Smart-SDK#print-a-custom-receipt
When I copy+paste the sample code and run it, noting happens.

https://github.com/developermypos/myPOS-Smart-SDK#receive-pos-info
registerPOSInfo also doesn't work

So I think I am missing something? 
Cannot find any documentation about it.

**Comment by DaSpors** [comment]
Now as the device is correctly activated everything works. Suggestion: Throw an Exception telling what to do instead of just do nothing ;)

**Comment by ditistijn** [comment]
hi there, I'm currently trying to debug an app on the Smart N5. How did you manage to enable the debug mode? I can't seem to find it in the settings. Thanks!

**Comment by DaSpors** [comment]
If i remember correctly the device needs to be registered and set up for development mode. Unfortunately i cannot help with how this works, because we had contact to some cto that helped bypass the normal procedure. 
So i recommend that you contact the devs directly.

**Comment by ditistijn** [comment]
thanks! can you recall that you had to get a separate developer unit, or did you use the regular production-ready terminal?

**Comment by DaSpors** [comment]
It was a regular unit that has been set to be a debug device.

**Comment by ditistijn** [comment]
Thanks!
