### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by niktses** [developermypos/myPOS-Smart-SDK#4]
I am developing an app for the myPos n5 and when i set the EditText input type to TYPE_TEXT_VARIATION_VISIBLE_PASSWORD the keyboard does not appear as intended. Is there a way for this to be fixed? I dont seen to be able to change anything related to the keyboard from the settings.

**Comment by jkatsiotis** [comment]
I'm also facing the same issue. I'm trying to have both numbers and letters appear on the keyboard at the same time in my N5 app. Any help would be much appreciated.

**Comment by developermypos** [comment]
In connection with the fact that you have a problem of a technical part of view, please send an e-mail to online@mypos.com to clarify the details around the issue
