### ISSUE TITLE
How to open the cash box with Hub+?

### ISSUE THREAD

**Issue by hugorosario** [developermypos/myPOS-Smart-SDK#9]
**What is the device you are using? Please describe.**
Using Hub+ device with a cash box connected to the RJ11 Cash Box port.

**Is your question related to a problem? Please describe.**
Cannot open the cash box.

**Describe the solutions you've tried**
Already tried sending the command "1B 70 00 40 F0" to the printer, but it does not work.

How can I send the kick/open command to the cash box?

**Comment by StiliyanKovachev** [comment]
try this: 
 
 context.sendBroadcast(new Intent("com.mypos.action.OPAN_CASH_DRAWER"));
